### ISSUE TITLE
Licenza mancante

### ISSUE THREAD

**Issue by garak** [paolobesser/tastiera-redazionale#1]
Per quanto sia comprensibile la volontà di tenere questo software sotto licenza freeware, ritengo che la presenza esplicita di un classico file `LICENSE.md` possa giovare.
L'unico riferimento compatibile che ho trovato è su [Wikipedia](https://en.wikipedia.org/wiki/Freeware#Relation_to_other_forms_of_software_licensing) e parla di CC.

Probabilmente (mio parere assolutamente personale) sarebbe più fattibile licenziare nel public domain e usare [unlicense](https://choosealicense.com/licenses/unlicense/), nel qual caso andrebbe modificato anche il file `README.md`

**Comment by paolobesser** [comment]
Hai ragione, adesso guardo meglio se ci sono restrizioni da parte di Microsoft (ma non credo proprio) e poi applico la licenza più liberale possibile.
